# Generated by Django 3.0.2 on 2020-05-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('stud_class', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
    ]
