# Generated by Django 3.0.2 on 2020-05-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.CharField(default='India', max_length=100),
        ),
    ]
